### PR TITLE
Datauri 2.0.0

### LINKED ISSUE #13: Cannot find module './old/module'
Hi guys,

I'm trying to use _datauri_, but I'm not able to import it.
Inserting
`var datauri = require('datauri');`

 in my files, the import produces the error 

`Cannot find module './old/module'`

Mu context:
- Node version: v5.10.1
- Ubuntu Linux
-  "datauri": "^1.0.4", via npm
- npm version: 3.8.3

Any suggestions ? 
Thanks in advance

### LINKED ISSUE #20: Cannot use within webpack
I'm using webpack to compile some serverside javascript. One of these files builds an `mjml` server that transitively depends on `datauri`. Webpack gives me the following error:

```
Module parse failed: .../node_modules/datauri/index.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
````

I can fix this in my webpack config, by writing a custom loader that takes the file and then deletes any beginning-#-lines. But note that of all the npm modules I'm using, this is the only one. I'll probably end up doing this to clean up this webpack error, and avoid blocking on this Issue.

From what I've seen in other threads, it's considered "bad practice" (according to The Internetz) to have a file act as both a script as well as a library module, for this reason.

I'm filing a bug, to track fixing this, or to close out my Issue as Working As Intended/Will Not Fix. :)

### PR DESCRIPTION
**Pull request by heldr**
- Drop support for deprecated and old Node.js versions.
  - 0.12
  - 0.10
- Remove babel build for module, use only Node.js 4+ code instead.
- Fix #13, since none file is compiled into /lib/old folder
- Possibly fix #20, since `#!/usr/bin/env node` only runs in cli script.
- Update dependencies to avoid warnings and bring security patches.

### CODE REVIEW

**Comment by SamBroner** [comment]
Is there any progress on this PR?

**Comment by heldr** [comment]
Not yet, I've been very busy with work. Gonna check ASAP!

**Comment by deadcoder0904** [comment]
Hey @heldr I think it can be published? Are there any issues in the PR that can't be published? 

I am getting an error due to the `#` shebang sign as I'm using it with Electron & Webpack. I would really appreciate if you can publish 2.0 :)

**Comment by deadcoder0904** [comment]
Also, I guess there is a mistake in the PR. `bin` in `package.json` is pointing to `index.js` whereas its in `./src/index.js` I guess

**Comment by heldr** [comment]
@deadcoder0904 Thanks for catching it and sorry for the big delay.

Gonna fix conflicts too and merge down this version.

**Pull request merged**
